### ISSUE TITLE
Databases?

### ISSUE THREAD

**Issue by warcrafte** [openlcoreteam/OpenLCore#8]
Hi where is it databases?

**Comment by Ramys** [comment]
I believe it is this.
@warcrafte 
https://github.com/AshamaneProject/AshamaneCore/releases
ADB_735.00
@Traesh Traesh released this on May 18, 2018 · 2040 commits to master since this release

**Comment by serayn** [comment]
https://github.com/openlcoreteam/OpenLCore/releases
Please use OpenLCore v0.1 database

**Comment by keivulan** [comment]
> https://github.com/openlcoreteam/OpenLCore/releases
> Please use OpenLCore v0.1 database
Hi,
I used the recommended database, but it reports an error.

In mysql_stmt_prepare() id: 62, sql: "INSERT INTO creature (guid, id , map, spawnDifficulties, PhaseId, PhaseGroup, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, spawndist, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, unit_flags2, unit_flags3, dynamicflags, movementmode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Unknown column 'movementmode' in 'field list'
